# Generated by Django 4.1.6 on 2023-02-09 15:25

import core.utils
from django.conf import settings
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.indexes
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text=(
                            "Допускаются только латинские буквы, цифры и символы"
                            " нижнего подчеркивания."
                        ),
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z_]*$",
                                (
                                    "Значение может состоять только из латинских букв,"
                                    " цифр и символов нижнего подчеркивания."
                                ),
                            )
                        ],
                        verbose_name="название",
                    ),
                ),
                (
                    "full_title",
                    models.CharField(
                        editable=False,
                        max_length=254,
                        unique=True,
                        verbose_name="полное название",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Любой комментарий для аналитика. Виден только тут.",
                        null=True,
                        verbose_name="комментарий",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        db_index=True,
                        help_text="Ярлык поля в UI.",
                        max_length=50,
                        verbose_name="ярлык",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор последнего изменения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text=(
                            "Пользователь сервиса, для которого создается данный"
                            " элемент."
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "поле",
                "verbose_name_plural": "      Поля",
                "ordering": ["full_title"],
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text=(
                            "Допускаются только латинские буквы, цифры и символы"
                            " нижнего подчеркивания."
                        ),
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z_]*$",
                                (
                                    "Значение может состоять только из латинских букв,"
                                    " цифр и символов нижнего подчеркивания."
                                ),
                            )
                        ],
                        verbose_name="название",
                    ),
                ),
                (
                    "full_title",
                    models.CharField(
                        editable=False,
                        max_length=254,
                        unique=True,
                        verbose_name="полное название",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Любой комментарий для аналитика. Виден только тут.",
                        null=True,
                        verbose_name="комментарий",
                    ),
                ),
                (
                    "ui",
                    models.JSONField(
                        default=core.utils.two_dimensional_list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text=(
                            "📍Интерфейс формы необходимо указать в виде валидного"
                            " двумерного JSON-массива.<br>📍Каждый вложенный массив"
                            " является строкой формы.<br>📍Каждый элемент в строке формы"
                            " должен являться строкой с значением полного названия"
                            " поля, начинающегося с символа '$'.<br>📍В строке может"
                            " быть максимум 6 полей.<br>📍Вы можете использовать пустые"
                            " строки в интерфейсе формы. Это будет пустое скрытое поле,"
                            " которое можно использовать, например, для сокращения"
                            " длины поля ввода текста в интерфейсе.<br>📍Пример"
                            " интерфейса формы: <code>[['$it-campaign_name-admin',"
                            " '$ch-is_geo-admin'], ['$ii-age_from-admin', '']]</code>."
                        ),
                        verbose_name="интерфейс формы",
                    ),
                ),
                (
                    "main_result_is_url",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Если эта настройка активна, то при генерации прометки"
                            " будут проделаны следующие действия с основным полем"
                            " результата:<br>📍Если в форме есть чекбокс"
                            " <code>'$use_https'</code> (владелец которого является"
                            " также владельцем формы), и он активен – принудительно"
                            " поменяется протокол на https<br>📍Повторные символы '?'"
                            " заменятся на символ '&'<br>📍Удалятся все дубли"
                            " слэшей<br>📍Результат будет провалидирован на корректность"
                            " URL. В случае ошибки к URL будет добавлено сообщение"
                            " '❗️URL НЕ ВАЛИДЕН❗'"
                        ),
                        verbose_name="основное поле результата является URL",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "main_result_field",
                    models.ForeignKey(
                        help_text=(
                            "Это поле будет выводиться самым первым в результатах"
                            " прометки. Обычно, это поле генерации полного URL, но"
                            " необязательно."
                        ),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_main_result_field",
                        to="core.field",
                        verbose_name="основное поле результата",
                    ),
                ),
            ],
            options={
                "verbose_name": "форма",
                "verbose_name_plural": " Формы",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="RawUtmData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                (
                    "utm_hashcode",
                    models.CharField(
                        editable=False,
                        max_length=8,
                        unique=True,
                        verbose_name="уникальный код ссылки",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        editable=False,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="данные для прометки",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.form",
                        verbose_name="форма",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор последнего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "сырые данные отправленной формы",
                "verbose_name_plural": "сырые данные отправленных форм",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "поле формы",
                "verbose_name_plural": "      Поля форм",
                "ordering": ["full_title"],
            },
            bases=("core.field",),
        ),
        migrations.CreateModel(
            name="ResultField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.field",
                    ),
                ),
                (
                    "clean_value",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Символы ['=', '&', '?', '#', ''', '\"'] будут удалены из"
                            " значения поля."
                        ),
                        verbose_name="удалить из значения поля специальные символы URL",
                    ),
                ),
                (
                    "disable_lowercase",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Значение поля не будет приведено к нижнему регистру во"
                            " время генерации UTM-прометки."
                        ),
                        verbose_name="не приводить к нижнему регистру",
                    ),
                ),
                (
                    "chars_settings",
                    models.CharField(
                        choices=[
                            ("not_set", "Ничего не делать"),
                            ("transliterate", "Транслитерация"),
                            ("urlencode", "Кодировка в urlencode"),
                        ],
                        default="transliterate",
                        max_length=13,
                        verbose_name="действие над полученным значением",
                    ),
                ),
                (
                    "add_hash",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Строка вида 'xxxxxxxx' с уникальным кодом ссылки будет"
                            " добавлена в значение правила генерации результата."
                        ),
                        verbose_name="добавить уникальный код ссылки",
                    ),
                ),
                (
                    "hash_separator",
                    models.CharField(
                        blank=True,
                        default="~",
                        help_text=(
                            "Символ(ы) (максимум 2), которые будут отделять уникальный"
                            " код ссылки от остального значения правила генерации"
                            " результата."
                        ),
                        max_length=2,
                        verbose_name="разделитель уникальной ссылки",
                    ),
                ),
                (
                    "separator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("_", "_"),
                            ("-", "-"),
                            ("|", "|"),
                            ("", "Не выбрано"),
                        ],
                        default="_",
                        help_text=(
                            "Символ, который будет разделять элементы в значении"
                            " правила генерации результата.<br>💡Разделитель применяется"
                            " к любому правилу генерации, присутствующему в данном"
                            " элементе."
                        ),
                        max_length=1,
                        verbose_name="разделитель",
                    ),
                ),
                (
                    "remove_blank_values",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Если при расчете правила генерации результата какие-либо"
                            " входящие в него поля дадут пустое значение – такие"
                            " значения будут удалены из значения правила генерации"
                            " результата.<br>💡Эту настройку следует отключить, если в"
                            " значении поля необходимо сохранить точное количество"
                            " входящих в него элементов (например, для последующего"
                            " парсинга)."
                        ),
                        verbose_name=(
                            "удалить пустые значения из правил генерации результата"
                        ),
                    ),
                ),
            ],
            options={
                "verbose_name": "поле генерации результата",
                "verbose_name_plural": "     Поля генерации результата",
                "ordering": ["full_title"],
            },
            bases=("core.field", models.Model),
        ),
        migrations.CreateModel(
            name="UtmResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                (
                    "main_result_value",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=1024,
                        verbose_name="результат прометки",
                    ),
                ),
                (
                    "result_fields_data",
                    models.JSONField(
                        default=list,
                        editable=False,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="значения полей результата",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "raw_utm_data",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.rawutmdata",
                        verbose_name="сырые данные отправленной формы",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор последнего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "результат прометки",
                "verbose_name_plural": "результаты прометки",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="SelectFormFieldDependence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text=(
                            "Допускаются только латинские буквы, цифры и символы"
                            " нижнего подчеркивания."
                        ),
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z_]*$",
                                (
                                    "Значение может состоять только из латинских букв,"
                                    " цифр и символов нижнего подчеркивания."
                                ),
                            )
                        ],
                        verbose_name="название",
                    ),
                ),
                (
                    "full_title",
                    models.CharField(
                        editable=False,
                        max_length=254,
                        unique=True,
                        verbose_name="полное название",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Любой комментарий для аналитика. Виден только тут.",
                        null=True,
                        verbose_name="комментарий",
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text=(
                            "Необходимо указать в виде валидного JSON-словаря: ключ"
                            " (key) – значение родительского поля, значение (value) –"
                            " массив ярлыков элементов зависимого поля, которые будут"
                            " показаны при выборе/установке указанного значения"
                            " родительского поля.<br>Если родительское поле – чекбокс,"
                            " то допустимые ключи только 'on' и 'off'."
                        ),
                        verbose_name="зависимые значения",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор последнего изменения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text=(
                            "Пользователь сервиса, для которого создается данный"
                            " элемент."
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "зависимость Select-поля",
                "verbose_name_plural": "  Зависимости Select-полей",
                "ordering": ["-pk"],
            },
        ),
        migrations.AddField(
            model_name="form",
            name="select_dependencies",
            field=models.ManyToManyField(
                blank=True,
                to="core.selectformfielddependence",
                verbose_name="зависимости select-полей",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор последнего изменения",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="user",
            field=models.ForeignKey(
                help_text=(
                    "Пользователь сервиса, для которого создается данный элемент."
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец",
            ),
        ),
        migrations.CreateModel(
            name="CheckboxFormField",
            fields=[
                (
                    "formfield_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.formfield",
                    ),
                ),
                (
                    "initial",
                    models.BooleanField(
                        default=False, verbose_name="включить по умолчанию"
                    ),
                ),
            ],
            options={
                "verbose_name": "поле Checkbox",
                "verbose_name_plural": "    Поля Checkbox",
                "ordering": ["-pk"],
            },
            bases=("core.formfield",),
        ),
        migrations.CreateModel(
            name="CombinedField",
            fields=[
                (
                    "resultfield_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.resultfield",
                    ),
                ),
                (
                    "build_rule",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text=(
                            "📍Правило генерации результата должно быть валидным"
                            " JSON-массивом с полными названиями полей и константами (в"
                            " виде строк) в том порядке, в котором они должны"
                            " появляться в сгенерированном значении.<br>📍Поля должны"
                            " быть указаны как full_name и должны начинаться с символа"
                            " '$'.<br>📍Пример: <code>['$it-campaign_name-admin',"
                            " 'some_value',"
                            " '$co-generated_ads_format-admin']</code>.<br>📍Правило"
                            " генерации результата также может содержать только одно"
                            " значение, оно должно быть указана так же в виде массива,"
                            " например: <code>['some_value']</code> или"
                            " <code>['$it-campaign_name-admin']</code>."
                        ),
                        verbose_name="правило генерации результата",
                    ),
                ),
            ],
            options={
                "verbose_name": "поле Combined",
                "verbose_name_plural": "  Поля Combined",
                "ordering": ["-pk"],
            },
            bases=("core.resultfield",),
        ),
        migrations.CreateModel(
            name="InputIntFormField",
            fields=[
                (
                    "formfield_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.formfield",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="обязательно к заполнению"
                    ),
                ),
                (
                    "tooltip",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Всплывающая подсказка при наведении курсора на поле."
                        ),
                        max_length=300,
                        verbose_name="тултип",
                    ),
                ),
                (
                    "initial",
                    models.IntegerField(
                        blank=True,
                        help_text=(
                            "Значение поля, которое будет установлено после загрузки"
                            " страницы формы с этим полем."
                        ),
                        null=True,
                        verbose_name="значение по умолчанию",
                    ),
                ),
                (
                    "placeholder",
                    models.IntegerField(
                        blank=True,
                        help_text="Подсказка в пустом поле.",
                        null=True,
                        verbose_name="плейсхолдер",
                    ),
                ),
            ],
            options={
                "verbose_name": "поле Input Int",
                "verbose_name_plural": "    Поля Input Int",
                "ordering": ["-pk"],
            },
            bases=("core.formfield",),
        ),
        migrations.CreateModel(
            name="InputTextFormField",
            fields=[
                (
                    "formfield_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.formfield",
                    ),
                ),
                (
                    "clean_value",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Символы ['=', '&', '?', '#', ''', '\"'] будут удалены из"
                            " значения поля."
                        ),
                        verbose_name="удалить из значения поля специальные символы URL",
                    ),
                ),
                (
                    "disable_lowercase",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Значение поля не будет приведено к нижнему регистру во"
                            " время генерации UTM-прометки."
                        ),
                        verbose_name="не приводить к нижнему регистру",
                    ),
                ),
                (
                    "chars_settings",
                    models.CharField(
                        choices=[
                            ("not_set", "Ничего не делать"),
                            ("transliterate", "Транслитерация"),
                            ("urlencode", "Кодировка в urlencode"),
                        ],
                        default="transliterate",
                        max_length=13,
                        verbose_name="действие над полученным значением",
                    ),
                ),
                (
                    "add_hash",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Строка вида 'xxxxxxxx' с уникальным кодом ссылки будет"
                            " добавлена в значение правила генерации результата."
                        ),
                        verbose_name="добавить уникальный код ссылки",
                    ),
                ),
                (
                    "hash_separator",
                    models.CharField(
                        blank=True,
                        default="~",
                        help_text=(
                            "Символ(ы) (максимум 2), которые будут отделять уникальный"
                            " код ссылки от остального значения правила генерации"
                            " результата."
                        ),
                        max_length=2,
                        verbose_name="разделитель уникальной ссылки",
                    ),
                ),
                (
                    "initial",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Значение поля, которое будет установлено после загрузки"
                            " страницы формы с этим полем."
                        ),
                        max_length=150,
                        verbose_name="значение по умолчанию",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="обязательно к заполнению"
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        help_text="Подсказка в пустом поле.",
                        max_length=150,
                        verbose_name="плейсхолдер",
                    ),
                ),
                (
                    "tooltip",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Всплывающая подсказка при наведении курсора на поле."
                        ),
                        max_length=300,
                        verbose_name="тултип",
                    ),
                ),
            ],
            options={
                "verbose_name": "поле Input Text",
                "verbose_name_plural": "    Поля Input Text",
                "ordering": ["-pk"],
            },
            bases=("core.formfield", models.Model),
        ),
        migrations.CreateModel(
            name="LookupTableField",
            fields=[
                (
                    "resultfield_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.resultfield",
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text=(
                            "📍Значение по умолчанию должно быть правилом генерации"
                            " результата.<br>📍Правило генерации результата должно быть"
                            " валидным JSON-массивом с полными названиями полей и"
                            " константами (в виде строк) в том порядке, в котором они"
                            " должны появляться в сгенерированном значении.<br>📍Поля"
                            " должны быть указаны как full_name и должны начинаться с"
                            " символа '$'.<br>📍Пример:"
                            " <code>['$it-campaign_name-admin', 'some_value',"
                            " '$co-generated_ads_format-admin']</code>.<br>📍Правило"
                            " генерации результата также может содержать только одно"
                            " значение, оно должно быть указана так же в виде массива,"
                            " например: <code>['some_value']</code> или"
                            " <code>['$it-campaign_name-admin']</code>."
                        ),
                        verbose_name="значение по умолчанию",
                    ),
                ),
                (
                    "lookup_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text=(
                            "📍Зависимые значения должны быть валидным"
                            " JSON-словарем.<br>📍Ключами (key) должны быть значения"
                            " поля, от которого зависит значение данного"
                            " поля.<br>📍Значения (values) должны быть правилом"
                            " генерации результата.<br>📍Правило генерации результата"
                            " должно быть валидным JSON-массивом с полными названиями"
                            " полей и константами (в виде строк) в том порядке, в"
                            " котором они должны появляться в сгенерированном"
                            " значении.<br>📍Поля должны быть указаны как full_name и"
                            " должны начинаться с символа '$'.<br>📍Пример:"
                            " <code>['$it-campaign_name-admin', 'some_value',"
                            " '$co-generated_ads_format-admin']</code>.<br>📍Правило"
                            " генерации результата также может содержать только одно"
                            " значение, оно должно быть указана так же в виде массива,"
                            " например: <code>['some_value']</code> или"
                            " <code>['$it-campaign_name-admin']</code>.<br>📍Если"
                            " lookup-поле зависит от checkbox, то имеет смысл указывать"
                            " зависимые значения только для включенного checkbox. Для"
                            " этого нужно указать в качестве ключа либо title"
                            " checkbox-поля, либо <code>'on'</code>. При выключенном"
                            " checkbox будет считаться значение по-умолчанию."
                        ),
                        null=True,
                        verbose_name="зависимые значения",
                    ),
                ),
            ],
            options={
                "verbose_name": "поле Lookup",
                "verbose_name_plural": "  Поля Lookup",
                "ordering": ["-pk"],
            },
            bases=("core.resultfield",),
        ),
        migrations.CreateModel(
            name="RadiobuttonFormField",
            fields=[
                (
                    "formfield_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.formfield",
                    ),
                ),
                (
                    "clean_value",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Символы ['=', '&', '?', '#', ''', '\"'] будут удалены из"
                            " значения поля."
                        ),
                        verbose_name="удалить из значения поля специальные символы URL",
                    ),
                ),
                (
                    "disable_lowercase",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Значение поля не будет приведено к нижнему регистру во"
                            " время генерации UTM-прометки."
                        ),
                        verbose_name="не приводить к нижнему регистру",
                    ),
                ),
                (
                    "chars_settings",
                    models.CharField(
                        choices=[
                            ("not_set", "Ничего не делать"),
                            ("transliterate", "Транслитерация"),
                            ("urlencode", "Кодировка в urlencode"),
                        ],
                        default="transliterate",
                        max_length=13,
                        verbose_name="действие над полученным значением",
                    ),
                ),
                (
                    "add_hash",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Строка вида 'xxxxxxxx' с уникальным кодом ссылки будет"
                            " добавлена в значение правила генерации результата."
                        ),
                        verbose_name="добавить уникальный код ссылки",
                    ),
                ),
                (
                    "hash_separator",
                    models.CharField(
                        blank=True,
                        default="~",
                        help_text=(
                            "Символ(ы) (максимум 2), которые будут отделять уникальный"
                            " код ссылки от остального значения правила генерации"
                            " результата."
                        ),
                        max_length=2,
                        verbose_name="разделитель уникальной ссылки",
                    ),
                ),
                (
                    "choices",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "Необходимо указать в виде валидного JSON-словаря: ключ"
                            " (key) – это ярлык (то, что будет выбирать пользователя),"
                            " значение (value) – это значение (то, что будет уходить в"
                            " прометчик)."
                        ),
                        null=True,
                        verbose_name="элементы поля",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="обязательно к заполнению"
                    ),
                ),
                (
                    "blank_value",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "К элементам поля будет добавлен элемент 'Не задано' с"
                            " пустым значением."
                        ),
                        verbose_name="добавить пустое значение",
                    ),
                ),
                (
                    "initial",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Значение (value) из JSON-словаря, элемент с которым будет"
                            " выбран автоматически после загрузки страницы формы с этим"
                            " полем"
                        ),
                        max_length=150,
                        verbose_name="значение по умолчанию",
                    ),
                ),
                (
                    "custom_input",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "К элементам поля будет добавлен элемент 'Указать"
                            " вручную...', при выборе которого появится поле для ввода"
                            " значения вручную."
                        ),
                        verbose_name="возможность задать значение вручную",
                    ),
                ),
            ],
            options={
                "verbose_name": "поле Radio Button",
                "verbose_name_plural": "   Поля Radio Button",
                "ordering": ["-pk"],
            },
            bases=("core.formfield", models.Model),
        ),
        migrations.CreateModel(
            name="SelectFormField",
            fields=[
                (
                    "formfield_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.formfield",
                    ),
                ),
                (
                    "clean_value",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Символы ['=', '&', '?', '#', ''', '\"'] будут удалены из"
                            " значения поля."
                        ),
                        verbose_name="удалить из значения поля специальные символы URL",
                    ),
                ),
                (
                    "disable_lowercase",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Значение поля не будет приведено к нижнему регистру во"
                            " время генерации UTM-прометки."
                        ),
                        verbose_name="не приводить к нижнему регистру",
                    ),
                ),
                (
                    "chars_settings",
                    models.CharField(
                        choices=[
                            ("not_set", "Ничего не делать"),
                            ("transliterate", "Транслитерация"),
                            ("urlencode", "Кодировка в urlencode"),
                        ],
                        default="transliterate",
                        max_length=13,
                        verbose_name="действие над полученным значением",
                    ),
                ),
                (
                    "add_hash",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Строка вида 'xxxxxxxx' с уникальным кодом ссылки будет"
                            " добавлена в значение правила генерации результата."
                        ),
                        verbose_name="добавить уникальный код ссылки",
                    ),
                ),
                (
                    "hash_separator",
                    models.CharField(
                        blank=True,
                        default="~",
                        help_text=(
                            "Символ(ы) (максимум 2), которые будут отделять уникальный"
                            " код ссылки от остального значения правила генерации"
                            " результата."
                        ),
                        max_length=2,
                        verbose_name="разделитель уникальной ссылки",
                    ),
                ),
                (
                    "choices",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "Необходимо указать в виде валидного JSON-словаря: ключ"
                            " (key) – это ярлык (то, что будет выбирать пользователя),"
                            " значение (value) – это значение (то, что будет уходить в"
                            " прометчик)."
                        ),
                        null=True,
                        verbose_name="элементы поля",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="обязательно к заполнению"
                    ),
                ),
                (
                    "blank_value",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "К элементам поля будет добавлен элемент 'Не задано' с"
                            " пустым значением."
                        ),
                        verbose_name="добавить пустое значение",
                    ),
                ),
                (
                    "initial",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Значение (value) из JSON-словаря, элемент с которым будет"
                            " выбран автоматически после загрузки страницы формы с этим"
                            " полем"
                        ),
                        max_length=150,
                        verbose_name="значение по умолчанию",
                    ),
                ),
                (
                    "custom_input",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "К элементам поля будет добавлен элемент 'Указать"
                            " вручную...', при выборе которого появится поле для ввода"
                            " значения вручную."
                        ),
                        verbose_name="возможность задать значение вручную",
                    ),
                ),
                (
                    "is_searchable",
                    models.BooleanField(
                        default=False, verbose_name="поиск по элементам поля"
                    ),
                ),
            ],
            options={
                "verbose_name": "поле Select",
                "verbose_name_plural": "   Поля Select",
                "ordering": ["-pk"],
            },
            bases=("core.formfield", models.Model),
        ),
        migrations.AddIndex(
            model_name="utmresult",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["result_fields_data"], name="core_utmres_result__ad800d_gin"
            ),
        ),
        migrations.AddField(
            model_name="selectformfielddependence",
            name="parent_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="select_formfield_dependence_parent_field",
                to="core.formfield",
                verbose_name="родительское поле",
            ),
        ),
        migrations.AddIndex(
            model_name="rawutmdata",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="core_rawutm_data_c9d75a_gin"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="result_fields",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text=None,
                to="core.resultfield",
                verbose_name="поля результата",
            ),
        ),
        migrations.AddConstraint(
            model_name="field",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_field"
            ),
        ),
        migrations.AddField(
            model_name="selectformfielddependence",
            name="child_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="select_formfield_dependence_child_field",
                to="core.selectformfield",
                verbose_name="зависимое поле",
            ),
        ),
        migrations.AddIndex(
            model_name="selectformfield",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["choices"], name="core_select_choices_a6647b_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="radiobuttonformfield",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["choices"], name="core_radiob_choices_49c223_gist"
            ),
        ),
        migrations.AddField(
            model_name="lookuptablefield",
            name="depends_field",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Поле формы, от значения которого зависит значение данного поля."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lookup_table_depends_field",
                to="core.field",
                verbose_name="зависит от",
            ),
        ),
        migrations.AddIndex(
            model_name="form",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["ui"], name="core_form_ui_bce9f9_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_form"
            ),
        ),
        migrations.AddIndex(
            model_name="combinedfield",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["build_rule"], name="core_combin_build_r_626faa_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="selectformfielddependence",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["values"], name="core_select_values_d2ec2f_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="selectformfielddependence",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_select_dependence"
            ),
        ),
        migrations.AddIndex(
            model_name="lookuptablefield",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["default_value"], name="core_lookup_default_52fded_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="lookuptablefield",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["lookup_values"], name="core_lookup_lookup__24bdb6_gin"
            ),
        ),
    ]
