version: '3'

services:
  utmcraft_postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
    restart: unless-stopped

  utmcraft_redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
    restart: unless-stopped

  utmcraft_web:
    build: ..
    command: sh -c "python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    python manage.py init_user &&
                    python manage.py loaddata core/fixtures/fields.yaml &&
                    python manage.py loaddata core/fixtures/form_fields.yaml &&
                    python manage.py loaddata core/fixtures/input_text_fields.yaml &&
                    python manage.py loaddata core/fixtures/input_int_fields.yaml &&
                    python manage.py loaddata core/fixtures/checkbox_fields.yaml &&
                    python manage.py loaddata core/fixtures/radio_button_fields.yaml &&
                    python manage.py loaddata core/fixtures/select_fields.yaml &&
                    python manage.py loaddata core/fixtures/select_dependences.yaml &&
                    python manage.py loaddata core/fixtures/result_fields.yaml &&
                    python manage.py loaddata core/fixtures/combined_fields.yaml &&
                    python manage.py loaddata core/fixtures/lookup_fields.yaml &&
                    python manage.py loaddata core/fixtures/forms.yaml &&
                    python manage.py loaddata authorization/fixtures/profiles.yaml &&
                    python manage.py loaddata client_admin/fixtures/client_admin.yaml &&
                    gunicorn configs.wsgi:application --bind 0.0.0.0:8000 -w ${GUNICORN_WORKERS_COUNT}"
    expose:
      - 8000
    volumes:
      - static_volume:/home/utmcraft/web/static
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - utmcraft_postgres
      - utmcraft_redis

  utmcraft_nginx:
    image: nginx
    volumes:
      - static_volume:/home/utmcraft/web/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - utmcraft_web

volumes:
  static_volume:
