# Generated by Django 4.1.6 on 2023-02-09 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_admin_access",
                    models.BooleanField(
                        default=False, verbose_name="доступ к клиентской админке"
                    ),
                ),
                (
                    "history_main_result_title",
                    models.CharField(
                        default="UTM-разметка",
                        help_text=(
                            "Название вкладки в Истории для основного результата"
                            " прометки.<br>Так же это значение подставится в Истории в"
                            " название колонки с основным полем результата."
                        ),
                        max_length=50,
                        verbose_name="название вкладки в Истории",
                    ),
                ),
                (
                    "forms",
                    sortedm2m.fields.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        to="core.form",
                        verbose_name="доступные формы",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль пользователя",
                "verbose_name_plural": "профили пользователей",
            },
        ),
    ]
